import { Clock, Mail, MapPin, Phone } from 'lucide-react'
import LegalModal from './LegalModal'
import { EMAIL, PHONE_DISPLAY, PHONE_HREF } from './site'

function Impressum() {
  return <LegalModal trigger="Impressum" title="Impressum" description="Angaben gemäß § 5 TMG / DDG"><div><h3 className="font-bold text-[#1D1D1F]">Angaben zum Unternehmen</h3><p>Krankenfahrdienst Koschmann Ambulance<br />Inhaber: Karim Koschmann (Einzelunternehmen)<br />Jacob-Weber-Straße 33<br />45307 Essen</p></div><div><h3 className="font-bold text-[#1D1D1F]">Kontakt</h3><p>Telefon: <a href={PHONE_HREF} className="text-[#A80000] hover:underline">{PHONE_DISPLAY}</a><br />E-Mail: <a href={`mailto:${EMAIL}`} className="text-[#A80000] hover:underline">{EMAIL}</a></p></div><div><h3 className="font-bold text-[#1D1D1F]">Genehmigung</h3><p>Genehmigung nach § 49 PBefG für Krankenfahrten ohne medizinisch-fachliche Betreuung.</p><p className="mt-2">Genehmigungsbehörde: zuständige Verkehrsbehörde<br /><span className="rounded bg-stone-100 px-2 py-0.5 text-sm text-stone-500">[Platzhalter: genaue Behörde und Genehmigungsnummer ergänzen]</span></p></div></LegalModal>
}

function Privacy() {
  return <LegalModal trigger="Datenschutz" title="Datenschutzerklärung" description="Informationen zur Datenverarbeitung"><div><h3 className="font-bold text-[#1D1D1F]">1. Verantwortlicher</h3><p>Karim Koschmann, Krankenfahrdienst Koschmann Ambulance, Jacob-Weber-Straße 33, 45307 Essen, Telefon: {PHONE_DISPLAY}, E-Mail: {EMAIL}</p></div><div><h3 className="font-bold text-[#1D1D1F]">2. Erhebung und Verarbeitung von Daten</h3><p>Beim Besuch dieser Website werden keine personenbezogenen Daten durch uns gespeichert oder ausgewertet. Es kommen keine Cookies und kein Tracking zum Einsatz.</p></div><div><h3 className="font-bold text-[#1D1D1F]">3. Kontaktaufnahme</h3><p>Bei telefonischer oder schriftlicher Kontaktaufnahme verarbeiten wir Ihre Angaben (z. B. Name, Kontaktdaten, Fahrtanlass) ausschließlich zur Bearbeitung Ihrer Anfrage und zur Durchführung der Krankenfahrt (Art. 6 Abs. 1 lit. b DSGVO). Eine Weitergabe an Dritte erfolgt nur, soweit dies für die Fahrtdurchführung oder Abrechnung mit Ihrer Krankenkasse erforderlich ist.</p></div><div><h3 className="font-bold text-[#1D1D1F]">4. Kartenmaterial</h3><p>Zur Darstellung unseres Einsatzgebiets wird Kartenmaterial von OpenStreetMap eingebunden. Beim Aufruf der Karte wird eine Verbindung zu den Servern der OpenStreetMap Foundation hergestellt; dabei wird Ihre IP-Adresse übermittelt.</p></div><div><h3 className="font-bold text-[#1D1D1F]">5. Ihre Rechte</h3><p>Sie haben jederzeit das Recht auf Auskunft, Berichtigung, Löschung und Einschränkung der Verarbeitung Ihrer personenbezogenen Daten sowie ein Beschwerderecht bei der zuständigen Aufsichtsbehörde.</p></div></LegalModal>
}

export default function Footer() {
  return <footer className="bg-[#2B0000] py-14 text-red-100/85" aria-label="Fußzeile"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-10 md:grid-cols-3"><div className="flex items-start gap-4"><img src="/assets/logo.jpeg" alt="" aria-hidden="true" className="h-16 w-16 rounded-full object-contain ring-2 ring-white/20" width="64" height="64" loading="lazy" /><div><p className="font-bold leading-snug text-white">Krankenfahrdienst<br />Koschmann Ambulance</p><p className="mt-1 text-sm text-red-100/60">Inhaber: Karim Koschmann</p><p className="text-sm text-red-100/60">Krankenfahrten in Essen und Umgebung – seit 2005</p></div></div><address className="not-italic"><p className="mb-3 text-sm font-bold uppercase tracking-widest text-red-100/50">Kontakt</p><p className="flex items-start gap-3"><MapPin className="mt-1 h-5 w-5 shrink-0 text-[#F87171]" /><span>Jacob-Weber-Straße 33<br />45307 Essen</span></p><p className="mt-3 flex items-center gap-3"><Phone className="h-5 w-5 shrink-0 text-[#F87171]" /><a href={PHONE_HREF} className="hover:text-white">{PHONE_DISPLAY}</a></p><p className="mt-3 flex items-center gap-3"><Mail className="h-5 w-5 shrink-0 text-[#F87171]" /><a href={`mailto:${EMAIL}`} className="hover:text-white">{EMAIL}</a></p></address><div><p className="mb-3 text-sm font-bold uppercase tracking-widest text-red-100/50">Erreichbarkeit &amp; Gebiet</p><p className="flex items-start gap-3"><Clock className="mt-1 h-5 w-5 shrink-0 text-[#F87171]" /><span>Montag bis Freitag<br />06:00 – 18:00 Uhr</span></p><p className="mt-3 flex items-start gap-3"><MapPin className="mt-1 h-5 w-5 shrink-0 text-[#F87171]" /><span>Einsatzgebiet: Essen und Umgebung</span></p><p className="mt-4 text-sm text-red-100/60">Krankenfahrten ohne medizinisch-fachliche Betreuung.<br />Kein Rettungsdienst. Im Notfall wählen Sie bitte die 112.</p></div></div><div className="mt-12 flex flex-col items-center justify-between gap-4 border-t border-white/10 pt-8 text-sm sm:flex-row"><p className="text-red-100/60">© {new Date().getFullYear()} Karim Koschmann – Krankenfahrdienst Koschmann Ambulance, Essen</p><div className="flex gap-6"><Impressum /><Privacy /></div></div></div></footer>
}
