import { useMemo } from 'react'
import L from 'leaflet'
import { Circle, MapContainer, Marker, Popup, TileLayer } from 'react-leaflet'
import { motion } from 'framer-motion'
import { MapPin } from 'lucide-react'
import 'leaflet/dist/leaflet.css'
import { EssenSkyline, LightLines } from './Decorations'

const markerPosition: [number, number] = [51.4686, 7.0565]
const mapCenter: [number, number] = [51.4556, 7.0116]

export default function ServiceArea() {
  const markerIcon = useMemo(() => L.divIcon({ className: '', html: '<div class="map-marker"><span>K</span></div>', iconSize: [44, 44], iconAnchor: [22, 42], popupAnchor: [0, -40] }), [])

  return <section id="einsatzgebiet" className="relative scroll-mt-24 overflow-hidden bg-white py-20 sm:py-28" aria-labelledby="einsatzgebiet-heading"><div aria-hidden="true" className="pointer-events-none absolute inset-x-0 top-0 h-64 bg-gradient-to-b from-[#F8EEEE]/90 to-transparent" /><LightLines variant="cross" boost={2} /><LightLines variant="cross" slow boost={1.5} /><EssenSkyline className="text-[#7A0000]/[0.07]" /><div aria-hidden="true" className="pointer-events-none absolute -left-40 top-10 h-[24rem] w-[24rem] rounded-full bg-[#A80000]/[0.06] blur-3xl" /><div aria-hidden="true" className="pointer-events-none absolute -right-40 top-0 h-[22rem] w-[22rem] rounded-full bg-[#C5161D]/[0.05] blur-3xl" />
    <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid items-center gap-10 lg:grid-cols-5 lg:gap-16"><motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: .6 }} className="lg:col-span-2"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#A80000]">Einsatzgebiet</p><h2 id="einsatzgebiet-heading" className="mt-3 text-3xl font-extrabold tracking-tight text-[#1D1D1F] sm:text-4xl">Wir sind in Essen und Umgebung für Sie unterwegs</h2><p className="mt-4 text-lg leading-relaxed text-[#57534e]">Wir fahren im gesamten Stadtgebiet Essen sowie in der näheren Umgebung.</p><div className="mt-8 space-y-4"><div className="flex items-start gap-4 rounded-2xl bg-white p-5 ring-1 ring-stone-200/80"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-red-50"><MapPin className="h-5 w-5 text-[#A80000]" /></span><div><p className="font-bold text-[#1D1D1F]">Unser Standort</p><p className="text-[#57534e]">Jacob-Weber-Straße 33<br />45307 Essen</p></div></div><div className="flex items-start gap-4 rounded-2xl bg-white p-5 ring-1 ring-stone-200/80"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-red-50"><MapPin className="h-5 w-5 text-[#A80000]" /></span><div><p className="font-bold text-[#1D1D1F]">Fahrgebiet</p><p className="text-[#57534e]">Essen und Umgebung – z. B. Mülheim, Bottrop, Gelsenkirchen, Bochum, Hattingen und Velbert.</p></div></div></div></motion.div>
      <motion.div initial={{ opacity: 0, scale: .97 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: .7 }} className="relative lg:col-span-3"><div aria-hidden="true" className="absolute -inset-4 rotate-1 rounded-[2rem] bg-gradient-to-br from-[#A80000]/[0.09] to-[#640000]/[0.05]" /><div aria-hidden="true" className="absolute -bottom-10 -right-10 h-56 w-56 rounded-full bg-[#C5161D]/[0.08] blur-2xl" /><div className="relative h-[26rem] overflow-hidden rounded-3xl shadow-xl ring-1 ring-stone-200 sm:h-[30rem]" role="region" aria-label="Interaktive Karte: Einsatzgebiet Essen und Umgebung"><MapContainer center={mapCenter} zoom={11} scrollWheelZoom={false} className="h-full w-full" attributionControl><TileLayer attribution='© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>-Mitwirkende' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Circle center={mapCenter} radius={7500} pathOptions={{ color: '#A80000', weight: 2, fillColor: '#A80000', fillOpacity: .08 }} /><Marker position={markerPosition} icon={markerIcon}><Popup><strong>Krankenfahrdienst Koschmann Ambulance</strong><br />Jacob-Weber-Straße 33, 45307 Essen</Popup></Marker></MapContainer></div></motion.div>
    </div></div>
  </section>
}
